SET C51INC=E:\mcu_keil\C51\Inc;E:\mcu_keil\C51\Inc\Atmel
SET C51LIB=E:\mcu_keil\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"E:\mcu_keil\C51\BIN\A51.EXE" @..\Output\STARTUP._ia
"E:\mcu_keil\C51\BIN\C51.EXE" @..\Output\delay.__i
"E:\mcu_keil\C51\BIN\C51.EXE" @..\Output\main.__i
"E:\mcu_keil\C51\BIN\C51.EXE" @..\Output\uart.__i
"E:\mcu_keil\C51\BIN\BL51.EXE" @..\Output\project.lnp
"E:\mcu_keil\C51\BIN\OH51.EXE" "..\Output\project" 
